---
- name: Install application dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nginx
    - python3-venv
    - python3-pip
    - git

- name: Create virtualenv directory
  ansible.builtin.file:
    path: "{{ app_venv_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv "{{ app_venv_path }}"
  args:
    creates: "{{ app_venv_path }}/bin/activate"

- name: Clone the application repository
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dest }}"
    version: "{{ app_repo_version | default('master') }}"
    force: yes
    update: yes

- name: Install Python requirements into venv
  ansible.builtin.pip:
    requirements: "{{ app_dest }}/requirements.txt"
    virtualenv: "{{ app_venv_path }}"
    virtualenv_python: python3

- name: Render Nginx site configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link

- name: Disable default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure Nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

# Instalacja i3WM:
- name: Ensure i3wm and utilities are installed
  ansible.builtin.apt:
    name:
      - i3
      - i3status
      - dmenu
      - i3lock
      - feh
    state: present
    update_cache: no
  tags: i3

- name: Ensure ~/.config/i3 exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags: i3

- name: Clone i3 configuration from GitHub
  ansible.builtin.git:
    repo: "{{ i3wm_config_repo }}"
    dest: "{{ ansible_env.HOME }}/.config/i3"
    version: "{{ i3wm_config_version }}"
    force: yes
    update: yes
  tags: i3

- name: Check if i3 config file exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/i3/config"
  register: i3config
  tags: i3

- name: Ensure ~/.i3 directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.i3"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags: i3

- name: Symlink i3 config to ~/.i3/config
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/i3/config"
    dest: "{{ ansible_env.HOME }}/.i3/config"
    state: link
    force: yes
  when: i3config.stat.exists
  tags: i3
