---
- name: Install application dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nginx
    - python3-pip
    - git

- name: Clone the application repository
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dest }}"
    version: "{{ app_repo_version | default('master') }}"

- name: Configure Nginx for the application
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
