---
- name: Włącz repozytorium restricted
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} restricted"
    filename: "ubuntu-restricted"
    state: present

- name: Zainstaluj narzędzia do PPA i wykrywania sterownika NVIDIA
  ansible.builtin.apt:
    name:
      - software-properties-common
      - dirmngr
      - ubuntu-drivers-common
    state: present
    update_cache: yes

- name: Dodaj PPA graphics‑drivers/ppa (sterowniki nVidia)
  ansible.builtin.command: add-apt-repository -y ppa:graphics-drivers/ppa

- name: Odśwież cache APT po dodaniu PPA
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Automatyczna instalacja rekomendowanego sterownika NVIDIA
  ansible.builtin.command: ubuntu-drivers autoinstall
  become: yes

- name: Odśwież cache APT
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalacja pozostałych pakietów bazowych
  ansible.builtin.apt:
    name:
      - vim
      - htop
      - curl
      - wget
      - snapd
      - gedit
      - terminator
      - smplayer
      - arduino
      - fritzing
      - caja
      - qbittorrent
      - gimp
      - freecad
      - sqlitebrowser
      - system-config-printer
      - printer-driver-postscript-hp
      - hplip
      - flatpak
      - gnome-software-plugin-flatpak
      - unattended-upgrades
    state: present

- name: Włącz Unattended Upgrades non‑interaktywnie
  ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
