---

- name: Install prerequisites for adding PPAs
  apt:
    name:
      - software-properties-common
      - dirmngr
    state: present
    update_cache: yes

- name: Add nVidia graphics‑drivers PPA GPG key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2388FF3BE10A76F638F80723FCAE110B1118213C
    state: present

- name: Add graphics‑drivers PPA (nVidia)
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present

- name: Add AppImageLauncher PPA
  apt_repository:
    repo: ppa:appimagelauncher-team/stable
    state: present

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install all base packages
  apt:
    name:
      - vim
      - htop
      - curl
      - wget
      - snapd
      - gedit
      - terminator
      - smplayer
      - arduino
      - fritzing
      - caja
      - qbittorrent
      - gimp
      - freecad
      - sqlitebrowser
      - system-config-printer
      - printer-driver-postscript-hp
      - hplip
      - flatpak
      - gnome-software-plugin-flatpak
      - nvidia-driver-535
      - appimagelauncher
      - unattended-upgrades
    state: present

- name: Enable Unattended Upgrades non‑interactively
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
