---
- name: Ensure basic tools are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - htop
    - curl
    - wget

- name: Ensure Unattended Upgrades is enabled
  apt:
    name: unattended-upgrades
    state: present

- name: Enable Unattended Upgrades
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
